# ASSALAMUALAYKUM IT'S ME MONIM 😉 #
# THIS SCRIPT WRITTEN BY MONIM #
#━━━━━━━━━━━━IMPORT━━━━━━━━━━━━#
import os,sys,time
try:
    import rich
except:
    os.system(" pip install rich ")
    import rich
from rich import print
from rich.panel import Panel
#━━━━━━━━━━━━LOGO━━━━━━━━━━━━#
logo = """╔═╗╔═╗╔╦╗  ╦ ╦╔═╗
╚═╗║╣  ║───║ ║╠═╝
╚═╝╚═╝ ╩   ╚═╝╩  """
#━━━━━━━━━━━━MAIN-DEF━━━━━━━━━━━━#
def main():
    os.system("clear")
    print(Panel.fit(logo))
    print(Panel.fit("DEVELOPER  : MUSHFIQUR RAHMAN MONIM\nGITHUB     : MUSHFIQUR RAHMAN MONIM\nTOOLS TYPE : TERMUX SETUP"))
    print(Panel.fit("[1] NORMAL SETUP\n[2] FULL SETUP "))
    option =input("└──> CHOICE YOUR OPTION :")
    if option in ["1","a","A"]:
        normal()
    elif option in ["2","b","B"]:
        full()
def normal():
    os.system("termux-setup-storage")
    os.system("apt update -y")
    os.system("apt upgrade -y")
    os.system("apt install python -y")
    os.system("apt uninstall python -y")
    os.system("pkg install git -y")
    os.system("pkg install php -y")
    os.system("pkg install curl -y")
    os.system("pkg install wget -y")
    os.system("pip2 install mechanize")
    os.system("pip2 install requests")
    os.system("pip2 install bs4")
    os.system("pip install requests")
    os.system("pip install mechanize")
    os.system("pip install bs4");sys.exit(Panel.fit("[red]NORMAL SETUP COMPLETE"))
def full():
    os.system("termux-setup-storage")
    os.system("pkg update -y")
    os.system("pkg upgrade -y")
    os.system("pkg install python -y")
    os.system("pkg install python2 -y")
    os.system("pkg install python3 -y")
    os.system("pkg install python-pip -y")
    os.system("pkg install wget -y")
    os.system("pkg install fish -y")
    os.system("pkg install ruby -y")
    os.system("pkg install help -y")
    os.system("pkg install git -y")
    os.system("pkg install dnsutils -y")
    os.system("pkg install php -y")
    os.system("pkg install perl -y")
    os.system("pkg install lua -y")
    os.system("pkg install parallel -y")
    os.system("pkg install nmap -y")
    os.system("pkg install bash -y")
    os.system("pkg install clang -y")
    os.system("pkg install nano -y")
    os.system("pkg install w3m -y")
    os.system("pkg install hydra -y")
    os.system("pkg install figlet -y")
    os.system("pkg install cowsay -y")
    os.system("pkg install curl -y")
    os.system("pkg install tar -y")
    os.system("pkg install zip -y")
    os.system("pkg install unzip -y")
    os.system("pkg install net-tools -y")
    os.system("pkg install tor -y")
    os.system("pkg install sudo -y")
    os.system("pkg install wireshark -y")
    os.system("pkg install wgetrc -y")
    os.system("pkg install wcalc -y")
    os.system("pkg install openssl -y")
    os.system("pkg install openssl-tool -y")
    os.system("pkg install bmon -y")
    os.system("pkg install vpn -y")
    os.system("pkg install unrar -y")
    os.system("pkg install toilet -y")
    os.system("pkg install proot -y")
    os.system("pkg install net-tools -y")
    os.system("pkg install vim -y")
    os.system("pkg install vim-python -y")
    os.system("pkg install ired -y")
    os.system("pkg install goaccess -y")
    os.system("pkg install golang -y")
    os.system("pkg install tar -y")
    os.system("pkg install kibi -y")
    os.system("pkg install tsu -y")
    os.system("pkg install tmux -y")
    os.system("pkg install mtools -y")
    os.system("pkg install file -y")
    os.system("pkg install vis -y")
    os.system("pkg install pass -y")
    os.system("pkg install pick -y")
    os.system("pkg install chroot -y")
    os.system("termux-chroot -y")
    os.system("pkg install macchanger -y")
    os.system("pkg install ninja -y")
    os.system("pkg install elixir -y")
    os.system("pkg install swift -y")
    os.system("pkg install xmlstarlet -y")
    os.system("pkg install fakeroot -y")
    os.system("pkg install texinfo -y")
    os.system("pkg install netcat -y")
    os.system("pkg install wren -y")
    os.system("pkg install gatling -y")
    os.system("pkg install cvs -y")
    os.system("pkg install ffmpeg -y")
    os.system("pkg install screen -y")
    os.system("pkg install neofetch -y")
    os.system("pkg install mariadb -y")
    os.system("pkg install picolisp -y")
    os.system("pkg install toilet -y")
    os.system("pkg install cmatrix -y")
    os.system("pkg install dropbear -y")
    os.system("pkg install openssh -y")
    os.system("pkg install python-pip -y")
    os.system("pip2 install wget -y")
    os.system("pip install bs4 -y")
    os.system("pip2 install bs4 -y")
    os.system("pip install requests -y")
    os.system("pip2 install requests -y")
    os.system("pip install mechanize -y")
    os.system("pip2 install mechanize -y")
    os.system("pip install php -y")
    os.system("pip2 install php -y");sys.exit(Panel.fit("[red]FULL SETUP COMPLETE "))
main()